#!/usr/bin/env bash
# A script that displays Best School 10 times but displays Best School and then Hi on a new line
x=1
while [ $x -le 10 ]
do
echo "Best School"
((x++))
if [ $x -eq 9 ]; then
    echo Best School
    echo Hi
fi
done
